name: Build

on:
  pull_request:
  push:
    #branches:
      #- main

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y gcc-arm-none-eabi ninja-build libsdl2-dev cmake gcc-arm-none-eabi

      - name: Build non-native targets
        run: |
          mkdir build-non-native
          cd build-non-native
          cat ../CMakeLists.txt
          cmake -DCMAKE_BUILD_TYPE=Release -DPLT_TARGET=rpipico -DCMAKE_TOOLCHAIN_FILE=../Platform/MTL/rpipico/toolchain.cmake ..
          cmake --build .
          ls -l Source/*.uf2

      - name: Build native target
        run: |
          mkdir build-native
          cd build-native
          cat ../CMakeLists.txt
          cmake -DCMAKE_BUILD_TYPE=Release -DPLT_TARGET=native ..
          cmake --build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-linux
          path: |
                 build-non-native/Source/*.uf2
                 build-native/Source/picoX7*
                 build-native/docs/Research/exp_dx7

  build-mac:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: |
          brew install cmake ninja sdl2
          
      - name: Build non-native targets
        run: |
          mkdir build-non-native
          cd build-non-native
          cat ../CMakeLists.txt
          export PATH=$PATH:/usr/local/bin
          export CXX=/usr/local/bin/arm-none-eabi-g++
          export CC=/usr/local/bin/arm-none-eabi-gcc
          export ASM=/usr/local/bin/arm-none-eabi-as
          cmake -DCMAKE_BUILD_TYPE=Release -DPLT_TARGET=rpipico -DCMAKE_TOOLCHAIN_FILE=../Platform/MTL/rpipico/toolchain.cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/sdl2 ..
          cmake --build .
          ls -l Source/*.uf2

      - name: Build native target
        run: |
          mkdir build-native
          cd build-native
          cat ../CMakeLists.txt
          export PATH=$PATH:/usr/local/bin
          export CXX=/usr/local/bin/arm-none-eabi-g++
          export CC=/usr/local/bin/arm-none-eabi-gcc
          export ASM=/usr/local/bin/arm-none-eabi-as
          cmake -DCMAKE_BUILD_TYPE=Release -DPLT_TARGET=native -DCMAKE_PREFIX_PATH=/usr/local/opt/sdl2 ..
          cmake --build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-mac
          path: |
                 build-non-native/Source/*.uf2
                 build-native/Source/picoX7*
                 build-native/docs/Research/exp_dx7
